### ISSUE TITLE
[BUG]客户端无法登录，提示Read Timed Out

### ISSUE THREAD

**Issue by hhhawa** [FPSMasterTeam/FPSMaster-v3#24]
![ee811dbc-f94c-4a90-860c-54e5ee3b52df](https://github.com/FPSMasterTeam/FPSMaster-v3/assets/164493311/f448de00-fc11-4557-a193-1a5786b5ed77)

**Comment by SuperSkidder** [comment]
这不是一个bug
确保客户端最新的情况下 若问题仍存在，请检查网络环境

**Comment by hhhawa** [comment]
我开了[steamcommunity](dogfight360.com)，请问是这个的问题吗？
